//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTodo_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zadania", Namespace="http://marek2222.com/Zadania")]
    [System.SerializableAttribute()]
    public partial class Zadania : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable TabelaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable Tabela {
            get {
                return this.TabelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TabelaField, value) != true)) {
                    this.TabelaField = value;
                    this.RaisePropertyChanged("Tabela");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZadaniaService")]
    public interface IZadaniaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadaniaService/PobierzZadania", ReplyAction="http://tempuri.org/IZadaniaService/PobierzZadaniaResponse")]
        MyTodo_Client.ServiceReference1.Zadania PobierzZadania();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadaniaService/PobierzZadania", ReplyAction="http://tempuri.org/IZadaniaService/PobierzZadaniaResponse")]
        System.Threading.Tasks.Task<MyTodo_Client.ServiceReference1.Zadania> PobierzZadaniaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZadaniaServiceChannel : MyTodo_Client.ServiceReference1.IZadaniaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZadaniaServiceClient : System.ServiceModel.ClientBase<MyTodo_Client.ServiceReference1.IZadaniaService>, MyTodo_Client.ServiceReference1.IZadaniaService {
        
        public ZadaniaServiceClient() {
        }
        
        public ZadaniaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZadaniaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZadaniaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZadaniaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyTodo_Client.ServiceReference1.Zadania PobierzZadania() {
            return base.Channel.PobierzZadania();
        }
        
        public System.Threading.Tasks.Task<MyTodo_Client.ServiceReference1.Zadania> PobierzZadaniaAsync() {
            return base.Channel.PobierzZadaniaAsync();
        }
    }
}
